name: Package Python Application for Test and Prod

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  package:
    runs-on: windows-latest
    strategy:
      matrix:
        env: [test, prod]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Set environment variables for test or prod
      shell: bash
      run: |
        if [ "${{ matrix.env }}" == "test" ]; then
          echo "EGYPT_URL=${{ secrets.EGYPT_URL_TEST }}" >> $GITHUB_ENV
          echo "DUBAI_URL=${{ secrets.DUBAI_URL_TEST }}" >> $GITHUB_ENV
        elif [ "${{ matrix.env }}" == "prod" ]; then
          echo "EGYPT_URL=${{ secrets.EGYPT_URL_PROD }}" >> $GITHUB_ENV
          echo "DUBAI_URL=${{ secrets.DUBAI_URL_PROD }}" >> $GITHUB_ENV
        fi
        echo "APP_ENV=${{ matrix.env }}" >> $GITHUB_ENV

    - name: Package the application
      run: |
        pyinstaller --onefile --windowed --name app-${{ matrix.env }} app.py

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-${{ matrix.env }}
        path: dist/app-${{ matrix.env }}.exe
